spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ash001x@gmail.com
    password: tyqc wnku umdy ubsl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true