apiVersion: apps/v1 # Describe the version of the api server
kind: Deployment # Telling what type of object we are creating so its deployment, we can also define types like service
metadata:
  name: spring-boot-k8s # Telling the name of the app this can be anything.
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s # We will use this same name when defining the service so this name is IMPORTANT
  replicas: 3 # we are telling K8s to create 3 pods in my cluster. Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s # Labels name should be same as the matching labels
    spec:
      containers:
        - name: spring-boot-k8s ## this will be name of my container
          image: darksharkash/simplerestapisb-k8s:latest # Give the docker image name and version.Image that will be used to containers in the cluster 
          imagePullPolicy: IfNotPresent # If we dont define this then image will be pulled from docker hub and now this will check our local and if not present then it will pull from docker hub
          ports:
            - containerPort: 8080 # The port that the container is running on  the cluster
