apiVersion: v1 # Kubernetes API version
kind: Service # type of  object. Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-k8s-service # this will be the name of the our service , we can give any name
spec:
  selector:
    app: spring-boot-k8s # this should be the name of the deployment selector matchlabel name IMPORTANT.
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service 
  type: NodePort # type of the service. (we can access the application with Node IP and Node port)